---
title: "Two sample proportion test report (single code)"
author: "Jenni"
date: "2026-06-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Two sided proportion hypothesis tesing.



```{r include=FALSE}
## Two sample proportion test code for two binary inputs

# the treatment arm total is denoted as n.tx
# the control arm total is denoted as n.ctrl
# the treatment arm response number is denoted as resp.tx
#the control arm response number is denoted as resp.ctrl

# threshold: this is the significance level, users can change it. By default it is 0.05

two_sample_proportion_test <- function(n.tx,n.ctrl,resp.tx,resp.ctrl,threshold= 0.05){
  
  if(n.tx < resp.tx |
     n.ctrl < resp.ctrl |
     any(is.na(c(n.tx,n.ctrl,resp.tx,resp.ctrl))) |
     any(c(n.tx, n.ctrl) <= 0) | any(c(resp.tx, resp.ctrl) < 0) |
     any(c(n.tx, n.ctrl, resp.tx, resp.ctrl) %% 1 != 0)){
        return("Error: Input invalid. Please check for the correct numerical values.")
    
     }

  contigency <- matrix(
    c(resp.tx,resp.ctrl,
      n.tx - resp.tx, n.ctrl - resp.ctrl),
    nrow = 2, byrow = TRUE)
  
  chisqtest <- suppressWarnings(chisq.test(contigency,correct = FALSE))
  fishertest <- suppressWarnings(fisher.test(contigency))
  
  if(all(chisqtest$expected >= 5)){
    p_value = chisqtest$p.value
    if(p_value < 0.001){
      p_level  = "less than 0.001 (***)"
    } else if(p_value < 0.01){
      p_level  = "less than 0.01 (**)"
    } else if (p_value < 0.05){
      p_level  = "less than 0.05 (*)"
    } else {
      p_level = as.character(round(p_value,4))
    }
    statistic = chisqtest$statistic
    statistic_label = "test statistic"
    if (p_value <= threshold) {
      hypothesis.test = "Chi squared test"
      result = "reject"
      diff = "sufficient"
      end = "Thus receiving treatment or not is associated with the response."
    } else{
      hypothesis.test = "Chi squared test"
      result = "fail to reject"
      diff = "no"
      end = "Thus receiving treatment or not is not associated with the response."
    } } else{
      p_value = fishertest$p.value
      if(p_value < 0.001){
        p_level  = "less than 0.001 (***)"
      } else if(p_value < 0.01){
        p_level  = "less than 0.01 (**)"
      } else if (p_value < 0.05){
        p_level  = "less than 0.05 (*)"
      } else {
        p_level  = as.character(round(p_value,4))
      }
      statistic = fishertest$estimate
      statistic_label = "odds ratio"
      if (p_value <= threshold) {
        hypothesis.test = "Fisher's exact test"
        result = "reject"
        diff = "sufficient"
        end = "Thus receiving treatment or not is associated with the response."
      } else{
        hypothesis.test = "Fisher's exact test"
        result = "fail to reject"
        diff ="no"
        end = "Thus receiving treatment or not is not associated with the response."
      }}
  
  return(paste0(
    "We are conducting a hypothesis testing question. We assume that the data represent a random sample from the population, ",
    "and the individual values in the sample are independent of each other. ",
    "We are interested in the two-sided hypothesis test of whether receiving treatments or not is associated with the response rate. ",
    "Our null hypothesis is that treatment groups and response rate are independent, ",
    "meaning that when the two are not associated, then regardless of the types of groups, ",
    "there should be the same rate of response within each group, ",
    "and the alternative hypothesis is that they are associated, so the response rates differ between the two groups. ",
    "In this study, each variable is a binary outcome, treatment/control, and response/no-response. There is a total of ",
    n.tx+n.ctrl, " individuals in the group. ",
    "We perform the hypothesis test using ", hypothesis.test,
    ". The response rate in the treatment arm is ", round(resp.tx/n.tx,3),
    ", and is ", round(resp.ctrl/n.ctrl,3), " in control group. ",
    "At the two sided significance level of ", threshold, ", and the sample size of ",
    n.tx, " in the treatment group and ", n.ctrl, " in the control group, we would get a ", statistic_label, " of ",
    round(statistic, 4), " and the associated p-value of the test is ", p_level, ". We conclude that we ", result,
    " the null hypothesis, and there is ", diff,
    " statistically significant evidence that the response rate differs between treatment and control groups. ", end))
         
}

```


Conclusion: `r two_sample_proportion_test(50,40,30,10)`
